name: WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

# Add these lines to give the action permission to update your README
permissions:
  contents: write

jobs:
  update-readme:
    name: Update Profile README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
